# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (c) 2026 Western Digital Corporation or its affiliates.
#
# Authors: Dennis Maisenbacher (dennis.maisenbacher@wdc.com)

apiVersion: v1
kind: ServiceAccount
metadata:
  name: registry-cleanup-sa
  namespace: "docker-registry"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: registry-cleanup-role
  namespace: "docker-registry"
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: registry-cleanup-rolebinding
  namespace: "docker-registry"
subjects:
  - kind: ServiceAccount
    name: registry-cleanup-sa
    namespace: "docker-registry"
roleRef:
  kind: Role
  name: registry-cleanup-role
  apiGroup: rbac.authorization.k8s.io
